# This is a basic workflow to help you get started with Actions

name: Repository SCA Scan

# Controls when the workflow will run
on:
  workflow_call:  # Enables this workflow to be called by other workflows
  workflow_dispatch:  # Allows manual triggering
    inputs:
      repo:
        description: 'GitHub repository to scan (e.g., owner/repo)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sca-testing:
    name: Repository SCA scan (${{ inputs.repo }})
    runs-on: ubuntu-latest
    env:
      SBOM_DIR: /tmp/sboms  # Define global SBOM directory
      TARGET_DIR: /tmp/target_repository

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup job summary
        run: |
          echo "## Repository SCA Scan" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** \`${{ inputs.repo }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**RFC**: [View RFC](https://docs.google.com/document/d/1bh9TLFB0AjGh17mj_C1KOmLYJw9RY_iUhox7Pk-yeU8/edit?pli=1&tab=t.0#heading=h.rnd972k0hiye)" >> $GITHUB_STEP_SUMMARY
          echo "### Job Summary:" >> $GITHUB_STEP_SUMMARY
          echo "This job performs a Software Composition Analysis (SCA) scan on a specified repository." >> $GITHUB_STEP_SUMMARY
          echo "- Clones the target repository and installs necessary dependencies." >> $GITHUB_STEP_SUMMARY
          echo "- Generates a Software Bill of Materials (SBOM) using a set of generation tools." >> $GITHUB_STEP_SUMMARY
          echo "- Uploads the generated SBOMs using datadog-ci to sca-api." >> $GITHUB_STEP_SUMMARY
          echo "- Saves the SBOM artifacts for manual analysis if necessary." >> $GITHUB_STEP_SUMMARY

      - name: Install dependencies
        run: $GITHUB_WORKSPACE/scripts/install_dependencies.sh

      - name: Clone remote repository
        run: git clone https://github.com/${{ inputs.repo }}.git $TARGET_DIR

      - name: Generate SBOMs
        run: $GITHUB_WORKSPACE/scripts/generate_sboms.sh

      - name: Upload SBOMs using Datadog CI
        run: $GITHUB_WORKSPACE/scripts/upload_sboms.sh
        env:
          DD_SITE: ${{ secrets.DD_SITE }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        
      - name: Save SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: /tmp/sboms

